server:
  port: 9090

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html # http://localhost:9090/webjars/swagger-ui/index.html
