spring:
  datasource:
    url: jdbc:h2:mem:store;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations: classpath:import.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      open-in-view: false
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        storage_engine: innodb
        use_sql_comments: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  swagger-ui:
    groups-order: DESC
